name: base
channels:
- conda-forge
dependencies:
- python=3.12
- numpy
- pandas
- matplotlib
- seaborn
- scikit-learn
- statsmodels
- jupyter
- jupyterlab
- plotly
- folium
- imbalanced-learn
- xgboost
- lightgbm
- requests
- wordcloud
- pip
- pip:
  - tensorflow
  - keras
  - torch
  - shap
  - xgboost
  - polar